const $=s=>document.querySelector(s),chat=$("#chat"),input=$("#input"),status=$("#status");
let identity="guest",history=[];
function key(){return "eva_history_"+identity}
function save(){localStorage.setItem(key(),JSON.stringify(history.slice(-60)))}
function add(role,text,scroll=true){$("#welcome")?.remove();const row=document.createElement("div");row.className="msg "+role;const av=document.createElement("div");av.className="avatar";av.textContent=role==="user"?"You":"E";const b=document.createElement("div");b.className="bubble";b.textContent=text;role==="user"?row.append(b,av):row.append(av,b);chat.append(row);if(scroll)chat.scrollTop=chat.scrollHeight;return b}
async function loadIdentity(){try{const r=await fetch("/api/auth",{credentials:"same-origin"}),d=await r.json();identity=d.role||"guest";$("#identity").textContent=identity==="owner"?"Owner: Alam":"Guest user";$("#ownerLogin").textContent=identity==="owner"?"🔓 Owner mode":"🔐 Owner Login";history=JSON.parse(localStorage.getItem(key())||"[]");history.forEach(m=>add(m.role,m.content,false))}catch{}}
async function send(text){text=text.trim();if(!text)return;input.value="";input.style.height="auto";add("user",text);history.push({role:"user",content:text});save();status.textContent="Eva is thinking…";const b=add("assistant","Thinking…");try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({messages:history})}),d=await r.json();if(!r.ok)throw Error(d.error||"AI unavailable");b.textContent=d.reply;history.push({role:"assistant",content:d.reply});save();status.textContent="Eva is ready";speak(d.reply)}catch(e){b.textContent="Eva ka AI brain abhi connected nahi hai. OPENAI_API_KEY configure karne ke baad real AI replies milengi.";status.textContent="AI connection needed"}}
$("#form").addEventListener("submit",e=>{e.preventDefault();send(input.value)});input.addEventListener("input",()=>{input.style.height="auto";input.style.height=Math.min(input.scrollHeight,130)+"px"});input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("#form").requestSubmit()}});document.querySelectorAll("[data-q]").forEach(x=>x.onclick=()=>send(x.dataset.q));
$("#ownerLogin").onclick=async()=>{if(identity==="owner"){await fetch("/api/auth",{method:"DELETE",credentials:"same-origin"});localStorage.removeItem("eva_history_owner");location.reload();return}const secret=prompt("Owner secret enter karein:");if(!secret)return;const r=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({secret})});const d=await r.json();if(!r.ok)return alert(d.error||"Owner login failed");location.reload()};
$("#new").onclick=()=>{history=[];save();location.reload()};$("#clear").onclick=()=>{history=[];save();location.reload()};
let speechEnabled=false;
function speak(text){if(!speechEnabled||!("speechSynthesis"in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=/[\u0900-\u097F]/.test(text)?"hi-IN":"en-IN";speechSynthesis.speak(u)}
function voice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return alert("Is browser me voice input supported nahi hai.");const r=new R();r.lang="hi-IN";r.onstart=()=>status.textContent="Listening…";r.onresult=e=>{input.value=e.results[0][0].transcript;input.dispatchEvent(new Event("input"));status.textContent="Eva is ready"};r.onerror=()=>status.textContent="Voice unavailable";r.start()}
$("#mic").onclick=voice;$("#voice").onclick=()=>{speechEnabled=!speechEnabled;$("#voice").textContent=speechEnabled?"🔊":"🎙";if(speechEnabled)speak("Voice mode on.")};loadIdentity();